# NextSploit Scanner Modules

MODULE_REGISTRY = {
    "67779": {
        "name": "CVE-2025-67779",
        "title": "DoS Incomplete Fix — Infinite Promise Loop (RSC Follow-up)",
        "module": "modules.cve_67779",
        "function": "scan",
    },
    "29927": {
        "name": "CVE-2025-29927",
        "title": "Middleware Auth Bypass",
        "module": "modules.cve_29927",
        "function": "scan",
    },
    "57822": {
        "name": "CVE-2025-57822",
        "title": "SSRF via Headers",
        "module": "modules.cve_57822",
        "function": "scan",
    },
    "34351": {
        "name": "CVE-2024-34351",
        "title": "SSRF via Server Actions Host",
        "module": "modules.cve_34351",
        "function": "scan",
    },
    "55183": {
        "name": "CVE-2025-55183",
        "title": "Source Code Exposure",
        "module": "modules.cve_55183",
        "function": "scan",
    },
    "55184": {
        "name": "CVE-2025-55184",
        "title": "DoS Detection (Passive)",
        "module": "modules.cve_55184",
        "function": "scan",
    },
    "66478": {
        "name": "CVE-2025-66478",
        "title": "RCE via RSC Flight Protocol",
        "module": "modules.cve_66478",
        "function": "scan",
    },
    "rsc": {
        "name": "RSC-Attack",
        "title": "RSC Protocol & Server Actions",
        "module": "modules.rsc_attack",
        "function": "scan",
    },
    "46982": {
        "name": "CVE-2024-46982",
        "title": "Cache Poisoning / Stored XSS",
        "module": "modules.cve_46982",
        "function": "scan",
    },
    "56332": {
        "name": "CVE-2024-56332",
        "title": "Pathname Middleware Auth Bypass",
        "module": "modules.cve_56332",
        "function": "scan",
    },
    "48068": {
        "name": "CVE-2025-48068",
        "title": "Dev Server Source Exposure",
        "module": "modules.cve_48068",
        "function": "scan",
    },
    "34350": {
        "name": "CVE-2024-34350",
        "title": "HTTP Request Smuggling Check",
        "module": "modules.cve_34350",
        "function": "scan",
    },
    "59471": {
        "name": "CVE-2025-59471",
        "title": "Image Optimizer DoS Check",
        "module": "modules.cve_59471",
        "function": "scan",
    },
    "23870": {
        "name": "CVE-2026-23870",
        "title": "DoS via RSC Deserialization",
        "module": "modules.cve_23870",
        "function": "scan",
    },
    "44575": {
        "name": "CVE-2026-44575",
        "title": "Middleware Bypass via Segment-Prefetch (.rsc)",
        "module": "modules.cve_44575",
        "function": "scan",
    },
    "23864": {
        "name": "CVE-2026-23864",
        "title": "DoS RSC Memory Exhaustion (FormData $K)",
        "module": "modules.cve_23864",
        "function": "scan",
    },
    "mg66": {
        "name": "GHSA-mg66-mrh9-m8jx",
        "title": "DoS PPR/Cache Components Deadlock",
        "module": "modules.ghsa_mg66",
        "function": "scan",
    },
    "45109": {
        "name": "CVE-2026-45109",
        "title": "Middleware Bypass via Turbopack (Incomplete Fix)",
        "module": "modules.cve_45109",
        "function": "scan",
    },
    "64645": {
        "name": "CVE-2026-64645",
        "title": "SSRF via rewrites()/redirects() Hostname Injection",
        "module": "modules.cve_64645",
        "function": "scan",
    },
    "64642": {
        "name": "CVE-2026-64642",
        "title": "Middleware Bypass via App Router + Turbopack + Single Locale",
        "module": "modules.cve_64642",
        "function": "scan",
    },
    "64641": {
        "name": "CVE-2026-64641",
        "title": "DoS App Router via Server Actions CPU Exhaustion",
        "module": "modules.cve_64641",
        "function": "scan",
    },
    "64649": {
        "name": "CVE-2026-64649",
        "title": "SSRF Server Actions via Host Header (Custom Node.js Server)",
        "module": "modules.cve_64649",
        "function": "scan",
    },
    "44573": {
        "name": "CVE-2026-44573",
        "title": "Pages Router i18n Data-Route Middleware Bypass",
        "module": "modules.cve_44573",
        "function": "scan",
    },
    "44578": {
        "name": "CVE-2026-44578",
        "title": "WebSocket Upgrade SSRF (Self-Hosted, 16.x only)",
        "module": "modules.cve_44578",
        "function": "scan",
    },
    "64643": {
        "name": "CVE-2026-64643",
        "title": "Server Action / use cache Endpoint ID Leak",
        "module": "modules.cve_64643",
        "function": "scan",
    },
    "64644": {
        "name": "CVE-2026-64644",
        "title": "DoS Image Optimization API via SVG",
        "module": "modules.cve_64644",
        "function": "scan",
    },
    "64646": {
        "name": "CVE-2026-64646",
        "title": "Unbounded SA Payload Edge Runtime Memory Exhaustion",
        "module": "modules.cve_64646",
        "function": "scan",
    },
    "64648": {
        "name": "CVE-2026-64648",
        "title": "Cache Confusion via fetch() Response Body Mismatch",
        "module": "modules.cve_64648",
        "function": "scan",
    },
    "64647": {
        "name": "CVE-2026-64647",
        "title": "Cache Confusion via Invalid UTF-8 Request Body",
        "module": "modules.cve_64647",
        "function": "scan",
    },
    "sourcemap": {
        "name": "SOURCEMAP-EXPOSURE",
        "title": "JavaScript Sourcemap Public Exposure",
        "module": "modules.sourcemap_exposure",
        "function": "scan",
    },
}

